# Generated by Django 2.2.7 on 2019-11-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcion',
            name='hora_funcion',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
    ]
